[project]
name = "space-traj-opt"
version = "0.1.0"
description = ""
authors = [{ name = "Hassan Arif", email = "hassanarif87@gmail.com" }]
readme = "README.md"
requires-python = ">=3.12,<3.14"
dependencies = [
	"numpy>=2.0.0,<3.0.0",
	"scipy>=1.11.4,<2.0.0",
	"pandas>=2.1.4,<3.0.0",
	"plotly>=5.18.0,<6.0.0",
	"jupyter>=1.0.0,<2.0.0",
	"pint>=0.23,<0.24",
	"sympy>=1.12,<2.0.0",
	"jax>=0.4.35,<0.5.0",
	"numba>=0.61.0,<0.62.0",
	"matplotlib>=3.10.0,<4.0.0",
]

[dependency-groups]
dev = [
	"pytest>=8.1.1,<9.0.0",
	"snakeviz>=2.2.2,<3.0.0",
]

[tool.setuptools]
package-dir = {"" = "src"}

[tool.setuptools.packages.find]
where = ["src"]
include = ["space_traj_opt*"]

[build-system]
requires = ["setuptools>=61"]
build-backend = "setuptools.build_meta"
